export const categories = [
  {
    name: "Phones",
    slug: "phones",
    image: "/categories/phone.jpg",
  },
  {
    name: "Smart Watches",
    slug: "watches",
    image: "/categories/watches.jpg",
  },
  {
    name: "Cameras",
    slug: "cameras",
    image: "/categories/camera.png",
  },
  {
    name: "Headphones",
    slug: "headphones",
    image: "/categories/headphones.png",
  },
  {
    name: "Computers",
    slug: "computers",
    image: "/categories/computers.jpg",
  },
  {
    name: "Gaming",
    slug: "gaming",
    image: "/categories/gaming.jpg",
  },
  {
    name: "TV",
    slug: "tv",
    image: "/categories/tv.jpg",
  },
  {
    name: "Hair Dryers",
    slug: "dryers",
    image: "/categories/drying.jpg",
  },
  {
    name: "Laptops",
    slug: "laptops",
    image: "/categories/laptops.png",
  },
];

export const products = [
  {
    name: "Apple iPhone 15",
    slug: "iphone-15",
    description:
      "Meet the Apple iPhone 15 smartphone. It will not leave you in trouble thanks to the emergency notification via satellite and the function of accident detection. Help will come at the right moment.",
    price: 844.07,
    discount: 850,
    brand: "Apple",
    categoryId: 1,
    stock: 20,
    images: [
      "/catalog/phones/iphone15.webp",
      "/catalog/phones/iphone15back.webp",
      "/catalog/phones/iphone15cam.webp",
      "/catalog/phones/iphone15front.webp",
    ],
    colors: ["#E2F2F5", "#EEEDEA", "#C7E7B2", "#FDE5E5", "#4D4E50"],
    memory: ["128GB", "256GB", "512GB"],
    popularity: 100,
  },
  {
    name: "Apple iPhone 15 Pro",
    slug: "iphone-15-pro",
    description:
      "The Apple iPhone 15 Pro smartphone is forged from titanium, a durable and lightweight material from which its sides are made. The A17 Pro chip guarantees incredible device performance. The programmable Action button provides quick access to your favorite function.",
    price: 1180.46,
    brand: "Apple",
    categoryId: 1,
    stock: 15,
    images: [
      "/catalog/phones/iphone15Pro.webp",
      "/catalog/phones/iphone15Proback.webp",
      "/catalog/phones/iphone15ProCam.webp",
      "/catalog/phones/iphone15ProFront.webp",
    ],
    colors: ["#ECEBE7", "#9C9A93", "#585F6F", "#454442"],
    memory: ["128GB", "256GB", "512GB", "1024GB"],
    popularity: 100,
  },
  {
    name: "Apple iPhone 16 Pro",
    slug: "iphone-16-pro",
    description:
      "The iPhone 16 Pro is built with Apple Intelligence, a personal intelligent system that helps you write, express yourself, and complete tasks effortlessly.",
    price: 1518.92,
    discount: 1550,
    brand: "Apple",
    categoryId: 1,
    stock: 30,
    images: [
      "/catalog/phones/iphone16pro.webp",
      "/catalog/phones/iphone16proback.webp",
      "/catalog/phones/iphone16procam.webp",
      "/catalog/phones/iphone16prot.webp",
    ],
    colors: ["#E1D3C5", "#E6E6E6", "#A4A19C", "#515151"],
    memory: ["128GB", "256GB", "512GB", "1024GB"],
    popularity: 99,
  },
  {
    name: "Samsung Galaxy S24 Ultra",
    slug: "samsung-s24-ultra",
    description:
      "The Samsung Galaxy S24 Ultra smartphone has a case protected from dust and moisture with titanium edges and a black glass back panel.",
    price: 1485.9,
    discount: 1500,
    brand: "Samsung",
    categoryId: 1,
    stock: 10,
    images: [
      "/catalog/phones/samsungS24Ultra.webp",
      "/catalog/phones/samsungS24Ultraback.webp",
      "/catalog/phones/samsungS24Ultracam.webp",
      "/catalog/phones/samsungS24Ultrafront.webp",
    ],
    colors: ["#ECEAE3", "#958E86", "#D5D4D7", "#3A3837"],
    memory: ["256GB", "512GB", "1024GB"],
    popularity: 98,
  },
  {
    name: "Samsung Galaxy A55",
    slug: "samsung-a55",
    description:
      "The Samsung Galaxy A55 5G 256 GB smartphone in a blue case is equipped with a 6.6” display with Corning Gorilla Glass Victus+ protective coating from scratches.",
    price: 474.65,
    brand: "Samsung",
    categoryId: 1,
    stock: 30,
    images: [
      "/catalog/phones/samsungA55.webp",
      "/catalog/phones/samsungA55back.webp",
      "/catalog/phones/samsungA55cam.webp",
      "/catalog/phones/samsungA55front.webp",
    ],
    colors: ["#E5EBF2", "#FDF3C0", "#1D212A", "#E8D2E7"],
    memory: ["128GB", "256GB"],
    popularity: 95,
  },
  {
    name: "Xiaomi Redmi Note 13",
    slug: "xiaomi-redmi-note-13",
    description:
      "The Xiaomi Redmi Note 13 smartphone with a blue design is equipped with a 6.67” AMOLED display and stereo speakers with Dolby Atmos technology.",
    price: 206.37,
    brand: "Xiaomi",
    categoryId: 1,
    stock: 30,
    images: [
      "/catalog/phones/xiaomi13.webp",
      "/catalog/phones/xiaomi13back.webp",
      "/catalog/phones/xiaomi13cam.webp",
      "/catalog/phones/xiaomi13front.webp",
    ],
    colors: ["#CADEC1", "#7093AF", "#3D3F41"],
    memory: ["128GB", "256GB"],
    popularity: 80,
  },
  {
    name: "POCO X6 Pro",
    slug: "poco-x6-pro",
    description:
      "The POCO X6 Pro smartphone in a classic black case supports the 5G format, so that communication always remains stable.",
    price: 361.15,
    discount: 370,
    brand: "Poco",
    categoryId: 1,
    stock: 10,
    images: [
      "/catalog/phones/pocoX6Pro.webp",
      "/catalog/phones/pocoX6Proback.webp",
      "/catalog/phones/pocoX6Procam.webp",
      "/catalog/phones/pocoX6Profront.webp",
    ],
    colors: ["#F5DD6E", "#8C8C8C", "#444547"],
    memory: ["256GB", "512GB"],
    popularity: 79,
  },
  {
    name: "OPPO Reno12 F 4G",
    slug: "oppo-reno12-f",
    description:
      "The OPPO Reno12 F 4G smartphone comes in a green plastic case. The IP64 dust and moisture protection class prevents moisture from entering the device, and the shell can withstand short-term exposure to water droplets.",
    price: 237.32,
    discount: 242.3,
    brand: "OPPO",
    categoryId: 1,
    stock: 20,
    images: [
      "/catalog/phones/oppoReno12.webp",
      "/catalog/phones/oppoReno12back.webp",
      "/catalog/phones/oppoReno12cam.webp",
      "/catalog/phones/oppoReno12front.webp",
    ],
    colors: ["#5D7C67", "#ECE4DF", "#27292A"],
    memory: ["256GB", "512GB"],
    popularity: 90,
  },
  {
    name: "HONOR Magic6 Pro",
    slug: "honor-magic6-pro",
    description:
      "The HONOR Magic6 Pro smartphone with 512 GB of internal memory displays content on a 6.8-inch display with a resolution of 2800x1280 pixels.",
    price: 1135.06,
    brand: "Honor",
    categoryId: 1,
    stock: 5,
    images: [
      "/catalog/phones/honorMagic6.webp",
      "/catalog/phones/honorMagic6back.webp",
      "/catalog/phones/honorMagic6cam.webp",
      "/catalog/phones/honorMagic6front.webp",
    ],
    colors: ["#A7B6AA", "#181818"],
    memory: ["512GB"],
    popularity: 85,
  },
  {
    name: "realme 13+ 5G",
    slug: "realme-13",
    description:
      "The realme 13+ 5G smartphone is equipped with an advanced 4nm chipset and has a high level of performance. Thanks to the significant performance gains of the main cores and graphics core, as well as a significant reduction in power consumption, even the most demanding games can be played.",
    price: 340.51,
    brand: "Realme",
    categoryId: 1,
    stock: 10,
    images: [
      "/catalog/phones/realme13.webp",
      "/catalog/phones/realme13back.webp",
      "/catalog/phones/realme13front.webp",
    ],
    colors: ["#D9C5B7", "#252233"],
    memory: ["256GB"],
    popularity: 85,
  },
  {
    name: "Apple Watch Series 10",
    slug: "apple-watch-series-10",
    description:
      "The Series 10 is an important milestone for the Apple Watch. The smartwatch features the largest and most advanced display to date, displaying more information on the screen than ever before.",
    price: 512.83,
    brand: "Apple",
    categoryId: 2,
    stock: 10,
    images: [
      "/catalog/watches/appleWatch.webp",
      "/catalog/watches/appleWatchfront.webp",
    ],
    colors: ["#CFADA1", "#9E9EA0"],
    memory: [],
    popularity: 90,
  },
  {
    name: "HONOR Watch 5",
    slug: "honor-watch-5",
    description:
      "The HONOR Watch 5 smartwatch features a 1.85 round AMOLED display with a dial redesign feature.",
    price: 165.09,
    brand: "Honor",
    categoryId: 2,
    stock: 15,
    images: [
      "/catalog/watches/honorWatch.webp",
      "/catalog/watches/honorWatchfront.webp",
    ],
    colors: ["#DBDDDE", "#EBDCD3", "#313033"],
    memory: ["4GB"],
    popularity: 90,
  },
  {
    name: "Canon EOS 2000D Kit 18-55mm",
    slug: "canon-18-55",
    description:
      "The Canon EOS 2000D Kit 18-55mm DC SLR camera combines advanced technology and functionality to produce clear cinematic video in Full HD and images with beautiful background blur.",
    price: 443.7,
    brand: "Canon",
    categoryId: 3,
    stock: 40,
    images: ["/catalog/cameras/canon.webp", "/catalog/cameras/canonfront.webp"],
    colors: [],
    memory: [],
    popularity: 95,
  },
  {
    name: "Nikon D780 Body",
    slug: "nikon-d780",
    description:
      "The Nikon D780 Body full-frame SLR camera in black is suitable for shooting in almost any environment.",
    price: 1644.79,
    brand: "Nikon",
    categoryId: 3,
    stock: 10,
    images: ["/catalog/cameras/nikon.webp", "/catalog/cameras/nikonfront.webp"],
    colors: [],
    memory: [],
    popularity: 90,
  },
  {
    name: "Apple AirPods 4 ANC",
    slug: "apple-airpods-4",
    description:
      "The TWS Apple Airpods 4 ANC headphones have an IP54 protected design. They are not afraid of exposure to dust, moisture, splashes of water and precipitation.",
    price: 256.99,
    discount: 260,
    brand: "Apple",
    categoryId: 4,
    stock: 10,
    images: ["/catalog/headphones/appleAirPods4.webp"],
    colors: [],
    memory: [],
    popularity: 90,
  },
  {
    name: "Samsung Galaxy Buds 3",
    slug: "samsung-galaxy-buds-3",
    description:
      "The TWS Samsung Galaxy Buds 3 headphones are made in a translucent grey case in the form of wear-friendly earbuds.",
    price: 159.33,
    discount: 161.2,
    brand: "Samsung",
    categoryId: 4,
    stock: 15,
    images: ["/catalog/headphones/samsungBuds3.webp"],
    colors: ["#F8F8FA", "#818386"],
    memory: [],
    popularity: 70,
  },
  {
    name: "ARDOR GAMING NEO M143",
    slug: "ardor-gaming-neo-m143",
    description:
      "The model configuration is based on a 6-core Intel Core i5-12400F processor, which is capable of simultaneously processing up to 12 computational information streams.",
    price: 735,
    brand: "ARDOR GAMING",
    categoryId: 5,
    stock: 5,
    images: [
      "/catalog/computers/ardorM143.webp",
      "/catalog/computers/ardorM143front.webp",
      "/catalog/computers/ardorM143t.webp",
    ],
    colors: [],
    memory: ["500GB", "1000GB"],
    popularity: 70,
  },
  {
    name: "ARDOR GAMING EVO X082",
    slug: "ardor-gaming-evo-x082",
    description:
      "PC ARDOR GAMING EVO is a gaming computer with a powerful configuration based on Intel Core i7.",
    price: 4677.39,
    brand: "ARDOR GAMING",
    categoryId: 5,
    stock: 8,
    images: [
      "/catalog/computers/ardorX082.webp",
      "/catalog/computers/ardorX082front.webp",
      "/catalog/computers/ardorX082t.webp",
    ],
    colors: [],
    memory: ["2500GB"],
    popularity: 50,
  },
  {
    name: "Microsoft Xbox Series S",
    slug: "microsoft-xbox-series-5",
    description:
      "The Microsoft Xbox Series S game console is compact in size and allows you to immerse yourself in exciting games with mesmerizing visual effects at 120 frames per second.",
    price: 431.75,
    brand: "Xbox",
    categoryId: 6,
    stock: 8,
    images: [
      "/catalog/gaming/xboxSeriesS.webp",
      "/catalog/gaming/xboxSeriesS1.webp",
      "/catalog/gaming/xboxSeriesS2.webp",
    ],
    colors: [],
    memory: ["512GB", "1024GB"],
    popularity: 80,
  },
  {
    name: "PlayStation 5 Pro",
    slug: "playstation-5-pro",
    description:
      "Play PS5 games with the most impressive graphics ever possible on a PlayStation console.",
    price: 1284.99,
    brand: "PlayStation",
    categoryId: 6,
    stock: 25,
    images: [
      "/catalog/gaming/playstation5Pro.webp",
      "/catalog/gaming/playstation5Pro1.webp",
      "/catalog/gaming/playstation5Pro2.webp",
    ],
    colors: [],
    memory: ["2000GB"],
    popularity: 80,
  },
  {
    name: "Xiaomi TV A Pro 55",
    slug: "xiaomi-tv-a-pro-55",
    description:
      "The Xiaomi TV A Pro 55 2025 LED TV is equipped with a 55-inch screen with QLED quantum dot technology and 4K UltraHD resolution.",
    price: 462.59,
    brand: "Xiaomi",
    categoryId: 7,
    stock: 50,
    images: [
      "/catalog/tv/xiaomi55.webp",
      "/catalog/tv/xiaomi55a.webp",
      "/catalog/tv/xiaomi55b.webp",
    ],
    colors: [],
    memory: [],
    popularity: 100,
  },
  {
    name: "TCL 55C755",
    slug: "tcl-55c755",
    description:
      "The TCL QD-Mini LED 55C755 is a visual masterpiece that presents amazingly vivid visual effects with realistic colors and ultra-high contrast ratio.",
    price: 873.79,
    discount: 880,
    brand: "TCL",
    categoryId: 7,
    stock: 10,
    images: [
      "/catalog/tv/tcl55.webp",
      "/catalog/tv/tcl55a.webp",
      "/catalog/tv/tcl55b.webp",
    ],
    colors: [],
    memory: [],
    popularity: 98,
  },
  {
    name: "Dyson Supersonic HD07",
    slug: "dyson-supersonic-hd07",
    description:
      "The Dyson Supersonic HD07 hair dryer is equipped with 5 nozzles that will help to add volume, smooth and gently dry curls.",
    price: 473,
    discount: 475,
    brand: "Dyson",
    categoryId: 8,
    stock: 5,
    images: [
      "/catalog/dryers/dyson.webp",
      "/catalog/dryers/dyson1.webp",
      "/catalog/dryers/dyson2.webp",
      "/catalog/dryers/dyson3.webp",
    ],
    colors: [],
    memory: [],
    popularity: 99,
  },
  {
    name: "ASUS TUF Gaming A15 FA507NV-LP025",
    slug: "asus-tuf-gaming-a15",
    description:
      "The ASUS TUF Gaming A15 FA507NV-LP025 laptop complies with MIL-STD-810H standards. It can withstand shaking, bumps, falls, temperature changes, and high humidity.",
    price: 1079.39,
    discount: 1080,
    brand: "ASUS",
    categoryId: 9,
    stock: 10,
    images: [
      "/catalog/laptops/asusA15.webp",
      "/catalog/laptops/asusA15a.webp",
      "/catalog/laptops/asusA15b.webp",
    ],
    colors: [],
    memory: ["512GB"],
    popularity: 88,
  },
  {
    name: "ASUS VivoBook 15 X1502ZA-BQ2346",
    slug: "asus-vivobook-15",
    description:
      "The silver-colored ASUS VivoBook 15 X1502ZA-BQ2346 laptop is equipped with an Intel Core i7-12700H processor and is suitable for working in graphics and computing programs.",
    price: 637.35,
    discount: 640.1,
    brand: "ASUS",
    categoryId: 9,
    stock: 23,
    images: [
      "/catalog/laptops/asusVivoBook15.webp",
      "/catalog/laptops/asusVivoBook15a.webp",
      "/catalog/laptops/asusVivoBook15b.webp",
    ],
    colors: [],
    memory: ["512GB"],
    popularity: 85,
  },
  {
    name: "MSI Katana GF76 B12UCR-821XRU",
    slug: "msi-katana-gf76",
    description:
      "The MSI Katana GF76 B12UCR-821XRU laptop offers computer enthusiasts high speed and performance when working in resource-intensive programs, running games and graphic content.",
    price: 986.87,
    discount: 990,
    brand: "MSI",
    categoryId: 9,
    stock: 12,
    images: [
      "/catalog/laptops/msiKatanaGF76.webp",
      "/catalog/laptops/msiKatanaGF76a.webp",
      "/catalog/laptops/msiKatanaGF76b.webp",
    ],
    colors: [],
    memory: ["512GB"],
    popularity: 88,
  },
  {
    name: "Apple MacBook Air",
    slug: "apple-macbook-air",
    description:
      "The Apple MacBook Air laptop has a compact aluminum body, and it weighs only 1.24 kg. At the same time, it has a 13.6-inch screen with an illumination sensor that adjusts its brightness.",
    price: 1347.7,
    discount: 1531.71,
    brand: "Apple",
    categoryId: 9,
    stock: 33,
    images: [
      "/catalog/laptops/macbookAir.webp",
      "/catalog/laptops/macbookAira.webp",
      "/catalog/laptops/macbookAirb.webp",
    ],
    colors: [],
    memory: ["256GB"],
    popularity: 75,
  },
  {
    name: "Apple MacBook Pro",
    slug: "apple-macbook-pro",
    description:
      "The MacBook Pro is surging ahead with the M3, M3 Pro and M3 Max chips. Created using 3-nanometer technology, they represent the most advanced chips ever created for personal computers.",
    price: 4087.32,
    discount: 4100,
    brand: "Apple",
    categoryId: 9,
    stock: 8,
    images: [
      "/catalog/laptops/macbookPro.webp",
      "/catalog/laptops/macbookProa.webp",
      "/catalog/laptops/macbookProb.webp",
    ],
    colors: ["#C9CACC", "#625F62"],
    memory: ["1000GB"],
    popularity: 70,
  },
];

export const specsData = [
  { slug: "iphone-15", key: "Display", value: '6.1", AMOLED, 60Hz' },
  { slug: "iphone-15", key: "Processor", value: "Apple A16 Bionic" },
  { slug: "iphone-15", key: "RAM", value: "6GB" },
  { slug: "iphone-15", key: "Battery", value: "3349mAh" },
  { slug: "iphone-15-pro", key: "Display", value: '6.1", AMOLED, 120Hz' },
  { slug: "iphone-15-pro", key: "Processor", value: "Apple A17 Pro" },
  { slug: "iphone-15-pro", key: "RAM", value: "8GB" },
  { slug: "iphone-15-pro", key: "Battery", value: "3274mAh" },
  { slug: "iphone-16-pro", key: "Display", value: '6.3", AMOLED, 120Hz' },
  { slug: "iphone-16-pro", key: "Processor", value: "Apple A18 Pro" },
  { slug: "iphone-16-pro", key: "RAM", value: "8GB" },
  { slug: "iphone-16-pro", key: "Battery", value: "3349mAh" },
  { slug: "samsung-s24-ultra", key: "Display", value: '6.8", AMOLED, 120Hz' },
  { slug: "samsung-s24-ultra", key: "Processor", value: "Snapdragon 8 Gen 3" },
  { slug: "samsung-s24-ultra", key: "RAM", value: "12GB" },
  { slug: "samsung-s24-ultra", key: "Battery", value: "5000mAh" },
  { slug: "samsung-a55", key: "Display", value: '6.6", AMOLED, 120Hz' },
  { slug: "samsung-a55", key: "Processor", value: "Samsung Exynos 1480" },
  { slug: "samsung-a55", key: "RAM", value: "8GB" },
  { slug: "samsung-a55", key: "Battery", value: "5000mAh" },
  {
    slug: "xiaomi-redmi-note-13",
    key: "Display",
    value: '6.67", AMOLED, 120Hz',
  },
  {
    slug: "xiaomi-redmi-note-13",
    key: "Processor",
    value: "Qualcomm Snapdragon 685",
  },
  {
    slug: "xiaomi-redmi-note-13",
    key: "RAM",
    value: "8GB",
  },
  {
    slug: "xiaomi-redmi-note-13",
    key: "Battery",
    value: "5000mAh",
  },
  { slug: "poco-x6-pro", key: "Display", value: '6.67", AMOLED, 120Hz' },
  {
    slug: "poco-x6-pro",
    key: "Processor",
    value: "MediaTek Dimensity 8300 Ultra",
  },
  { slug: "poco-x6-pro", key: "RAM", value: "12GB" },
  { slug: "poco-x6-pro", key: "Battery", value: "5000mAh" },
  { slug: "oppo-reno12-f", key: "Display", value: '6.67", AMOLED, 120Hz' },
  {
    slug: "oppo-reno12-f",
    key: "Processor",
    value: "Qualcomm Snapdragon 685",
  },
  { slug: "oppo-reno12-f", key: "RAM", value: "8GB" },
  { slug: "oppo-reno12-f", key: "Battery", value: "5000mAh" },
  { slug: "honor-magic6-pro", key: "Display", value: '6.8", OLED, 120Hz' },
  {
    slug: "honor-magic6-pro",
    key: "Processor",
    value: "Qualcomm Snapdragon 8 Gen 3",
  },
  { slug: "honor-magic6-pro", key: "RAM", value: "12GB" },
  { slug: "honor-magic6-pro", key: "Battery", value: "5600mAh" },
  { slug: "realme-13", key: "Display", value: '6.67", OLED, 120Hz' },
  {
    slug: "realme-13",
    key: "Processor",
    value: "MediaTek Dimensity 7300 Energy",
  },
  { slug: "realme-13", key: "RAM", value: "12GB" },
  { slug: "realme-13", key: "Battery", value: "5000mAh" },
  { slug: "apple-watch-series-10", key: "Display", value: '1.77", OLED' },
  {
    slug: "apple-watch-series-10",
    key: "Processor",
    value: "Apple S10",
  },
  { slug: "honor-watch-5", key: "Display", value: '1.85", AMOLED' },
  { slug: "honor-watch-5", key: "Processor", value: "MediaTek" },
  { slug: "canon-18-55", key: "Pixels", value: "24.7MP" },
  { slug: "canon-18-55", key: "Video", value: "Full HD (1920 x 1080)" },
  { slug: "canon-18-55", key: "Lens", value: "Yes" },
  { slug: "nikon-d780", key: "Pixels", value: "25.28MP" },
  { slug: "nikon-d780", key: "Video", value: "4K UHD (3840 x 2160)" },
  { slug: "nikon-d780", key: "Lens", value: "No" },
  { slug: "apple-airpods-4", key: "Bluetooth", value: "5.3" },
  { slug: "samsung-galaxy-buds-3", key: "Bluetooth", value: "5.4" },
  {
    slug: "ardor-gaming-neo-m143",
    key: "Processor",
    value: "Intel Core i5-12400F",
  },
  {
    slug: "ardor-gaming-neo-m143",
    key: "Motherboard",
    value: "Intel H610",
  },
  {
    slug: "ardor-gaming-neo-m143",
    key: "RAM",
    value: "16GB",
  },
  {
    slug: "ardor-gaming-neo-m143",
    key: "Videocard",
    value: "GeForce RTX 3050",
  },
  {
    slug: "ardor-gaming-evo-x082",
    key: "Processor",
    value: "Intel Core i7-14700KF",
  },
  {
    slug: "ardor-gaming-evo-x082",
    key: "Motherboard",
    value: "Intel Z790",
  },
  {
    slug: "ardor-gaming-evo-x082",
    key: "RAM",
    value: "64GB",
  },
  {
    slug: "ardor-gaming-evo-x082",
    key: "Videocard",
    value: "GeForce RTX 4090",
  },
  {
    slug: "microsoft-xbox-series-5",
    key: "Processor",
    value: "AMD Ryzen Zen 2",
  },
  {
    slug: "microsoft-xbox-series-5",
    key: "Videocard",
    value: "AMD Radeon RDNA 2",
  },
  {
    slug: "microsoft-xbox-series-5",
    key: "RAM",
    value: "10GB",
  },
  {
    slug: "playstation-5-pro",
    key: "Processor",
    value: "AMD Ryzen Zen 2",
  },
  {
    slug: "playstation-5-pro",
    key: "Videocard",
    value: "RDNA",
  },
  {
    slug: "playstation-5-pro",
    key: "RAM",
    value: "16GB",
  },
  { slug: "xiaomi-tv-a-pro-55", key: "Display", value: '55", QLED, 60Hz' },
  { slug: "xiaomi-tv-a-pro-55", key: "Smart", value: "Android TV" },
  { slug: "xiaomi-tv-a-pro-55", key: "Sound", value: "DTS HD, Dolby Audio" },
  { slug: "tcl-55c755", key: "Display", value: '55", QLED, 120Hz' },
  { slug: "tcl-55c755", key: "Smart", value: "Google TV" },
  {
    slug: "tcl-55c755",
    key: "Sound",
    value: "DTS:X, Dolby Atmos, Dolby Audio",
  },
  { slug: "dyson-supersonic-hd07", key: "Power", value: "1600WT" },
  { slug: "asus-tuf-gaming-a15", key: "Display", value: '15.6", IPS, 144Hz' },
  {
    slug: "asus-tuf-gaming-a15",
    key: "Processor",
    value: "AMD Ryzen 5 7535HS",
  },
  {
    slug: "asus-tuf-gaming-a15",
    key: "RAM",
    value: "16GB",
  },
  {
    slug: "asus-tuf-gaming-a15",
    key: "Videocard",
    value: "GeForce RTX 4060",
  },
  { slug: "asus-vivobook-15", key: "Display", value: '15.6", IPS, 60Hz' },
  { slug: "asus-vivobook-15", key: "Processor", value: "Intel Core i7-12700H" },
  { slug: "asus-vivobook-15", key: "RAM", value: "16GB" },
  {
    slug: "asus-vivobook-15",
    key: "Videocard",
    value: "Intel Iris Xe Graphics",
  },
  { slug: "msi-katana-gf76", key: "Display", value: '17.3", IPS, 144Hz' },
  { slug: "msi-katana-gf76", key: "Processor", value: "Intel Core i5-12450H" },
  { slug: "msi-katana-gf76", key: "RAM", value: "16GB" },
  {
    slug: "msi-katana-gf76",
    key: "Videocard",
    value: "GeForce RTX 3050",
  },
  { slug: "apple-macbook-air", key: "Display", value: '13.6", IPS, 60Hz' },
  {
    slug: "apple-macbook-air",
    key: "Processor",
    value: "Apple M3",
  },
  { slug: "apple-macbook-air", key: "RAM", value: "8GB" },
  { slug: "apple-macbook-air", key: "Videocard", value: "Apple M3 8-core" },
  {
    slug: "apple-macbook-pro",
    key: "Display",
    value: '16.2", mini-LED, 120Hz',
  },
  { slug: "apple-macbook-pro", key: "Processor", value: "Apple M3 Max" },
  { slug: "apple-macbook-pro", key: "RAM", value: "48GB" },
  {
    slug: "apple-macbook-pro",
    key: "Videocard",
    value: "Apple M3 Max 40-core",
  },
];

export const reviews = [
  {
    rating: 5,
    comment:
      "This phone is just space! The camera shoots like a professional camera, the battery lasts for two days, and the screen is so bright that even in the sun everything is visible. I've been using it for a month now — not a single hang!",
    productId: 1,
    userId: 1,
  },
  {
    rating: 5,
    comment:
      "The best Android smartphone I've ever had! The performance is excellent, the stereo sound is just chic, and the shell is free of unnecessary debris. I am very pleased with the purchase!",
    productId: 4,
    userId: 1,
  },
  {
    rating: 5,
    comment:
      "I bought an iPhone 15 Pro a couple of months ago, and I'm generally satisfied. The camera is simply gorgeous, especially the night mode. Performance is at an altitude — any games and applications fly. The only negative is that it gets a little hot under load, but it's gotten better since the last update.",
    productId: 2,
    userId: 1,
  },
  {
    rating: 5,
    comment:
      "I really liked the new titanium case — it feels cool in my hand. The camera just captures space, and the screen is super bright. But the battery does not last as long as we would like. If you actively use it, by the evening 10-15% remains.",
    productId: 2,
    userId: 3,
  },
  {
    rating: 4,
    comment:
      "The iPhone 16 Pro is still the best smartphone, but I expected more. Yes, the processor is more powerful, the camera has improved, but there are few visual changes. I would like a bigger upgrade. If you have a 15 Pro, I don't see any point in updating.",
    productId: 3,
    userId: 3,
  },
];
